import app1 from './assets/demo-app__1_.webp'
import app2 from './assets/demo-app__2_.webp'
import app3 from './assets/demo-app__3_.webp'
import app4 from './assets/demo-app__4_.webp'
import app5 from './assets/demo-app__5_.webp'
import app6 from './assets/demo-app__6_.webp'

export const apps = [
  {
    id: 1,
    name: 'Pomodoro Timer For Productivity',
    category: 'Productivity',
    rating: 4.8,
    reviews: 2341,
    downloads: '1.2M',
    size: '24 MB',
    version: '3.2.1',
    icon: app4,
    installed: true,
    description: `Pomodoro Timer is the ultimate productivity companion designed to help you stay focused and manage your time effectively. Based on the proven Pomodoro Technique, this app breaks your work into focused intervals separated by short breaks.\n\nBoost your concentration, eliminate distractions, and track your progress with detailed statistics. Whether you're a student, professional, or creative, Pomodoro Timer adapts to your workflow.\n\nKey Features:\n• Customizable work and break intervals\n• Detailed productivity statistics\n• Task management integration\n• White noise and focus sounds\n• Streak tracking and achievements`,
    screenshots: [app1, app2, app3],
    badge: 'Editor\'s Choice',
  },
  {
    id: 2,
    name: 'SmPlan:ToDo List With Reminder',
    category: 'Productivity',
    rating: 4.9,
    reviews: 5420,
    downloads: '6M',
    size: '18 MB',
    version: '5.0.3',
    icon: app6,
    installed: true,
    description: `SmPlan is a beautifully designed to-do list and task manager with smart reminders. Organize your life with ease using intuitive lists, subtasks, and powerful scheduling features.\n\nSync across all your devices and never miss a deadline again. SmPlan integrates with your calendar to give you a complete picture of your day.\n\nKey Features:\n• Smart reminders and notifications\n• Calendar integration\n• Subtasks and checklists\n• Priority levels and tags\n• Team collaboration features`,
    screenshots: [app2, app3, app5],
    badge: 'Top Pick',
  },
  {
    id: 3,
    name: 'FGF - Focus Flow For Study',
    category: 'Education',
    rating: 4.6,
    reviews: 1870,
    downloads: '890K',
    size: '31 MB',
    version: '2.1.0',
    icon: app2,
    installed: false,
    description: `Focus Flow is designed specifically for students who want to maximize their study sessions. Combines proven study techniques with ambient sounds to create the perfect learning environment.\n\nTrack your study streaks, set daily goals, and see your progress over time with beautiful analytics.\n\nKey Features:\n• Pomodoro & time-blocking modes\n• Ambient study sounds\n• Subject-based tracking\n• Study streak system\n• Weekly performance reports`,
    screenshots: [app1, app4, app6],
    badge: null,
  },
  {
    id: 4,
    name: 'Pomcat: Cute Pomodoro Timer',
    category: 'Productivity',
    rating: 4.7,
    reviews: 3200,
    downloads: '2.1M',
    size: '15 MB',
    version: '1.9.5',
    icon: app1,
    installed: false,
    description: `Pomcat brings a playful twist to the classic Pomodoro technique. With adorable cat companions that cheer you on, staying productive has never been more fun.\n\nCollect cat stickers as rewards for completing focus sessions and unlock new themes as you build your productivity streak.\n\nKey Features:\n• Cute cat companion system\n• Collectible rewards\n• Customizable timer sounds\n• Progress-based unlockables\n• Gentle focus reminders`,
    screenshots: [app2, app5, app3],
    badge: 'Fan Favorite',
  },
  {
    id: 5,
    name: 'Time Farmer: Schedule & Tasks',
    category: 'Productivity',
    rating: 4.5,
    reviews: 980,
    downloads: '540K',
    size: '28 MB',
    version: '1.4.2',
    icon: app3,
    installed: false,
    description: `Time Farmer gamifies your productivity by turning tasks into a farming adventure. Plant seeds (tasks), water them (work sessions), and harvest crops (completions) to grow your virtual farm.\n\nA unique and motivating way to stay on top of your daily responsibilities while having fun.\n\nKey Features:\n• Gamified task management\n• Virtual farm ecosystem\n• Daily quest system\n• Social leaderboards\n• Cross-platform sync`,
    screenshots: [app4, app1, app6],
    badge: null,
  },
  {
    id: 6,
    name: 'Morning Habit - Daily Routine',
    category: 'Health & Fitness',
    rating: 4.8,
    reviews: 4100,
    downloads: '3.4M',
    size: '22 MB',
    version: '4.0.1',
    icon: app5,
    installed: false,
    description: `Morning Habit helps you build powerful morning routines that set you up for success. Design your ideal morning with guided habits, timers, and motivational content.\n\nJoin millions of people who have transformed their lives with consistent morning routines powered by Morning Habit.\n\nKey Features:\n• Guided routine builder\n• Habit streak tracking\n• Morning meditation library\n• Motivational quotes and tips\n• Routine sharing with friends`,
    screenshots: [app2, app3, app1],
    badge: 'Top Rated',
  },
  {
    id: 7,
    name: 'Focus Plant: Todolist Tamer',
    category: 'Productivity',
    rating: 4.6,
    reviews: 2760,
    downloads: '1.8M',
    size: '19 MB',
    version: '2.7.0',
    icon: app2,
    installed: true,
    description: `Focus Plant grows a virtual garden as you complete your tasks and focus sessions. Each completed task blooms a new plant, building a beautiful garden that represents your productivity journey.\n\nStay motivated with a living visual representation of your hard work and dedication.\n\nKey Features:\n• Garden growth system\n• Deep focus mode\n• Task priority system\n• Weekly garden reports\n• Plant collection unlocks`,
    screenshots: [app5, app4, app3],
    badge: null,
  },
  {
    id: 8,
    name: 'Alarmy - Alarm Clock & Sleep',
    category: 'Health & Fitness',
    rating: 4.4,
    reviews: 8900,
    downloads: '10M+',
    size: '45 MB',
    version: '6.1.2',
    icon: app6,
    installed: false,
    description: `Alarmy is the world's most annoying alarm app — and that's exactly the point. With missions you must complete to silence the alarm, you'll never oversleep again.\n\nFrom math problems to shaking your phone to scanning a barcode in your kitchen, Alarmy makes sure you're truly awake.\n\nKey Features:\n• Wake-up missions\n• Sleep tracking\n• Gradual volume increase\n• Multiple alarm types\n• Sleep quality analysis`,
    screenshots: [app1, app2, app4],
    badge: 'Most Popular',
  },
]

export const installedApps = apps.filter(a => a.installed)
export const trendingApps = apps.slice(0, 6)
